-- [NEW] Analytics Events Table
CREATE TABLE IF NOT EXISTS public.analytics_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    type text NOT NULL, -- 'view', 'click'
    link_id bigint REFERENCES public.links(id) ON DELETE SET NULL, -- Optional, only for type='click'
    meta jsonb, -- To store user_agent, referrer, country, etc.
    created_at timestamptz DEFAULT now()
);

-- Enable RLS for Analytics
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

-- Analytics Policies
-- 1. Insert: Public (anyone can track a view/click) - Ideally authenticated anonymously or public endpoint handles it
-- Since our API will likely use service_role or handle auth check, proper RLS for public insert might be tricky.
-- Use case: "API Route" inserts using service_role, OR "Public User" inserts via anon key.
-- Let's allow public insert for now to support client-side tracking if needed, 
-- BUT robust way is API route with service_role bypass or specific allow.
-- Let's stick to: "Profiles" can view their own analytics.
DROP POLICY IF EXISTS "Users can view their analytics" ON public.analytics_events;
CREATE POLICY "Users can view their analytics" ON public.analytics_events FOR SELECT USING (auth.uid() = profile_id);

-- Depending on implementation (API route vs Client Insert), we might need an INSERT policy.
-- If we use the API route with `supabase-admin` (service role), we don't need RLS policies for insert.
-- If we use the public client, we need:
DROP POLICY IF EXISTS "Public can insert stats" ON public.analytics_events;
CREATE POLICY "Public can insert stats" ON public.analytics_events FOR INSERT WITH CHECK (true);

-- Index for performance (filtering by profile and date)
CREATE INDEX IF NOT EXISTS idx_analytics_profile_date ON public.analytics_events (profile_id, created_at);
