-- Forms and Form Submissions Schema

-- Forms table to store form configurations
CREATE TABLE IF NOT EXISTS public.forms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    link_id bigint REFERENCES public.links(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    destination_email text,
    fields jsonb NOT NULL, -- Array of form fields with their configuration
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Form submissions table to store all form responses
CREATE TABLE IF NOT EXISTS public.form_submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id bigint NOT NULL REFERENCES public.forms(id) ON DELETE CASCADE,
    profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    data jsonb NOT NULL, -- Form field responses as key-value pairs
    submitted_at timestamptz DEFAULT now(),
    read boolean DEFAULT false,
    ip_address text,
    user_agent text
);

-- Indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_forms_profile_id ON public.forms(profile_id);
CREATE INDEX IF NOT EXISTS idx_forms_link_id ON public.forms(link_id);
CREATE INDEX IF NOT EXISTS idx_form_submissions_form_id ON public.form_submissions(form_id);
CREATE INDEX IF NOT EXISTS idx_form_submissions_profile_id ON public.form_submissions(profile_id);
CREATE INDEX IF NOT EXISTS idx_form_submissions_submitted_at ON public.form_submissions(submitted_at DESC);

-- Enable RLS
ALTER TABLE public.forms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_submissions ENABLE ROW LEVEL SECURITY;

-- RLS Policies for forms
DROP POLICY IF EXISTS "Users can view own forms" ON public.forms;
CREATE POLICY "Users can view own forms" ON public.forms
    FOR SELECT USING (auth.uid() = profile_id);

DROP POLICY IF EXISTS "Users can manage own forms" ON public.forms;
CREATE POLICY "Users can manage own forms" ON public.forms
    FOR ALL USING (auth.uid() = profile_id);

-- RLS Policies for form_submissions
DROP POLICY IF EXISTS "Users can view own form submissions" ON public.form_submissions;
CREATE POLICY "Users can view own form submissions" ON public.form_submissions
    FOR SELECT USING (auth.uid() = profile_id);

DROP POLICY IF EXISTS "Public can insert form submissions" ON public.form_submissions;
CREATE POLICY "Public can insert form submissions" ON public.form_submissions
    FOR INSERT WITH CHECK (true); -- Allow public submissions

DROP POLICY IF EXISTS "Users can update own form submissions" ON public.form_submissions;
CREATE POLICY "Users can update own form submissions" ON public.form_submissions
    FOR UPDATE USING (auth.uid() = profile_id);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger to auto-update updated_at
DROP TRIGGER IF EXISTS update_forms_updated_at ON public.forms;
CREATE TRIGGER update_forms_updated_at
    BEFORE UPDATE ON public.forms
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
